### ISSUE TITLE
User card icons aren't centered

### ISSUE THREAD

**Issue by patrickh39** [NYRI4/Comfy-theme#18]
![image](https://user-images.githubusercontent.com/61527626/105614111-00761a80-5d7c-11eb-9c73-75b58e56fe3c.png)

**Comment by piotr25691** [comment]
Well, it's not really perfectly centered on me too.
![obraz](https://user-images.githubusercontent.com/71488561/105627035-6f16af00-5e34-11eb-91ee-0120fc139dca.png)

**Comment by marcpinet** [comment]
For me, it is well centered, see :

![ez](https://i.imgur.com/NVMSEBk.png)

**Comment by piotr25691** [comment]
You can fix this (at least it did fix for me) by entering this CSS into your custom CSS:
```css
#app-mount .header-QKLPzZ .wrapper-3t9DeA, .header-QKLPzZ .nameTag-2IFDfL, .activityHeader-1PExlk, .customStatusText-39gdCI, .actionButton-3W1xZa, .container-q03LZO .profileBadges-2vWUyB {
 margin: auto 20px;
 }
 ```
